---

- name: Ensure base Plex directory exists
  ansible.builtin.file:
    path: "{{ plex_docker_base_directory }}"
    state: 'directory'
    owner: "{{ plex_docker_user }}"
    group: "{{ plex_docker_user }}"
    mode: '0755'

- name: Ensure Plex compose file is present
  ansible.builtin.template:
    src: 'compose.yml.j2'
    dest: "{{ plex_docker_base_directory }}/compose.yml"
    owner: "{{ plex_docker_user }}"
    group: "{{ plex_docker_user }}"
    mode: '0644'
    backup: true
  register: plex_docker_compose_template_result

- name: Ensure Plex compose project is deployed
  community.docker.docker_compose_v2:
    project_src: "{{ plex_docker_base_directory }}"
    state: 'present'
    pull: "{{ 'always' if plex_docker_update_image else plex_docker_pull_policy }}"
    recreate: "{{ 'always' if (plex_docker_compose_template_result.changed or plex_docker_update_image) else 'auto' }}"
    remove_orphans: true
